# Generated by Django 4.1.3 on 2022-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options_alter_user_email_alter_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "staffs",
            },
        ),
    ]
