# Generated by Django 4.1.3 on 2022-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="num",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
