# Generated by Django 4.1.3 on 2022-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_rename_contents_medicine_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicine",
            old_name="content",
            new_name="effect",
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicineImg",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="takeMedicine",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="use",
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name="medicine",
            table=None,
        ),
    ]
