# Generated by Django 4.1.3 on 2022-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicine",
            "0003_rename_content_medicine_effect_medicine_medicineimg_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicineImg",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
